My attempt at the Etch a Sketch Project

Couple thoughts on this. I wasn't clear on the instructions as to whether or not there should be a trailing mouseout action.  Considering how etch-a-sketches themselves work, I decided to leave it out, and just have a clear button to clear the board.

I also would like to avoid having an extra div to represent the row, I thought flexbox would be able to do it in a single pass, but I couldnt' figure out either how to dynamically adjust the height or the width and kept running into css issues.

Other than that, enjoy!~